### ISSUE TITLE
You can't see what an icon looks like when you select it

### ISSUE THREAD

**Issue by MeuJia** [fluttercommunity/font_awesome_flutter#104]

**Comment by michaelspiss** [comment]
Hi, I'm not quite sure what the problem is. Could you please give some more details regarding what you are trying to do and where the icons don't show?

**Comment by MeuJia** [comment]
Icons can be used normally, but when you select icons, you can't find the specific icons. At this point, flutter's official ios icon is very good, and you can choose what you want according to the displayed icons

**Comment by michaelspiss** [comment]
Sorry, I still don't get what you mean by "when you select icons". Your IDE's autocompletion should display a list of possible icon names when you type `FontAwesomeIcons.`. We do not offer any other ways to "select" icons other than this. If I am misunderstanding what you mean, please attach a screenshot of your iOS example above

**Comment by MeuJia** [comment]
![image](https://user-images.githubusercontent.com/49261544/87285800-8d692d00-c52a-11ea-9ba9-32c6864f5e0c.png)
For example, the icon that comes with the official can see the icon when you choose it

**Comment by michaelspiss** [comment]
Ah, thanks. This is a [known problem](https://github.com/flutter/flutter-intellij/issues/2334) with the flutter plugin (feel free to upvote!). We sadly cannot do anything about it from our side.
