### ISSUE TITLE
Icons don't show up inside column class for some reason

### ISSUE THREAD

**Issue by Toufiqahmed** [fluttercommunity/font_awesome_flutter#106]
![Flutter Icons Problem](https://user-images.githubusercontent.com/20010346/86540007-f34c2800-bf1e-11ea-99eb-1928dde0bba9.jpg)
Hi , I've created a custom widget and I'm adding icons and want to put them inside the column,however the icons don't show up however If I don't use Column , the icons does show up (check 2nd Expanded widget),I don't know what exactly the issue is.

**Comment by michaelspiss** [comment]
Please use `FaIcon` instead of `Icon`, this is especially important when using non-square icons.
Does the issue persist when wrapping the icon in a `Container`?

**Comment by Toufiqahmed** [comment]
Hi, I don't know what but after I used FaIcon or something with padding I removed,it worked perfectly as it is supposed to be!
Please find the attached screenshot. Sorry for the trouble.Thank you for the quick response. Closing the issue.
![ProblemSolved](https://user-images.githubusercontent.com/20010346/86625131-33c0aa00-bfe2-11ea-8509-a52df6bca0c1.jpg)
