### ISSUE TITLE
Stacking and rotating etc 

### ISSUE THREAD

**Issue by ghenry** [fluttercommunity/font_awesome_flutter#107]
Hi,

Is this possible? 

https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons?

Thanks.

**Comment by michaelspiss** [comment]
Hi,

As everything in flutter, icons are only widgets. This means you can use everything flutter has to offer on them. To overlap icons use a [Stack](https://api.flutter.dev/flutter/widgets/Stack-class.html), for rotation [Transform.rotate](https://api.flutter.dev/flutter/widgets/Transform/Transform.rotate.html) might be useful.
