### ISSUE TITLE
FAQ clarification on location for FontAwesome Pro Metadata

### ISSUE THREAD

**Issue by bobwith2bees** [fluttercommunity/font_awesome_flutter#109]
In the FAQ, the directory location for the icons.json is ambiguous.  I picked the wrong directory, but figured it out.  Hoping to make the next person's experience a little better.

### From the FAQ - How can I use Pro Icons?
> Move icons.json from metadata _to this directory_
> Run ./tool/update.sh

The update.sh tool expects the location of icons.json to be in the current working directory.   It runs without errors and overwrites the files staged above.  Suggest changing the FAQ wording change to say:

Move icons.json from metadata directory to **the /path/to/your/font_awesome_flutter.**
From this directory run ./tool/update.sh.

**Comment by michaelspiss** [comment]
Thanks for mentioning this, it should be clearer now
