### ISSUE TITLE
Flutter random import statement

### ISSUE THREAD

**Issue by cup-a-snot** [fluttercommunity/font_awesome_flutter#110]
**VSC INFO**
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.10-arch1-1
Flutter Module: 3.13.1
Dart Module: 3.13.1

Essentially, every time I use a Font Awesome icon,
![usage](https://user-images.githubusercontent.com/69155039/89190889-1c88c400-d570-11ea-8a50-89d3ac819550.png)

I get a random import statement inserted in the import section of my code.
![randomImport](https://user-images.githubusercontent.com/69155039/89190946-32968480-d570-11ea-82fe-ff5bee6bad82.png)

Any ideas?

Cheers,
CAS

**Comment by michaelspiss** [comment]
Hi, this is a [problem with the dart analyzer](https://github.com/dart-lang/sdk/issues/39848) that was fixed december 2019. You may want to make sure you are running the latest version of flutter (close vsc, run `flutter upgrade` in the terminal). If the issue still persists after that, please open an issue over at the [dart sdk repository](https://github.com/dart-lang/sdk/issues/39848).
