### ISSUE TITLE
Asset icons

### ISSUE THREAD

**Issue by ghenry** [fluttercommunity/font_awesome_flutter#111]
Hi all,

I'm looking to use FA as asset icons for use with https://pub.dev/packages/quick_actions

Is it possible to extra from the ttf somehow?

Thanks.

**Comment by ghenry** [comment]
So on android it would be a drawable and on iOS an XCode Image.asset etc.

**Comment by michaelspiss** [comment]
Hi, Font awesome provides svg and png versions for each icon. You can download them from the official font awesome homepage.

**Comment by ghenry** [comment]
Apologies. I knew this. I don't know why I didn't engage my brain. Thanks for the reminder.

**Comment by michaelspiss** [comment]
No problem, glad I could help
