### ISSUE TITLE
Will it automatically remove unused icons in the released app?

### ISSUE THREAD

**Issue by fzyzcjy** [fluttercommunity/font_awesome_flutter#112]
Hi thanks for the library! I wonder whether it will automatically remove those unused icons? For instance, say I only use the "heart" icon. Then IMHO the final app should only contain this icon, instead of thousands of icons.

Thanks!

P.S. I have read the README but cannot find related info :/

**Comment by michaelspiss** [comment]
Hi, the answer is yes and no.
The icons are provided as fonts. Each icon style has its own file. Those files cannot be altered by our code and will always contain all icon "images". The only way to reduce their size is to use tools like [icomoon](https://icomoon.io), hand pick the icons you need, and install them like pro icons (see faq, skip steps with icons.json/running the generator). If you only use one icon, I would skip this package and just use the svg/png version of the icon I want to use from [font awesome](https://fontawesome.com). 

On the other hand, if you use only say "solid" style icons, the release version of your app will only include this style and not the files for "regular" or "brands" style icons. This is done automatically and does not require any further configuration. Additionally, all links (eg. `FontAwesomeIcons.abacus`) to unused icons will be removed, which means only the icon definitions your really want are loaded into ram.

I know this is fairly complex, so if you have further questions feel free to ask.

**Comment by fzyzcjy** [comment]
Thanks for the detailed reply! Get it!

**Comment by fzyzcjy** [comment]
I suddenly see this post releasing flutter 1.20 https://github.com/flutter/flutter/pull/56633 . It says

> this release fixes a tooling performance issue with icon font tree shaking and makes font tree shaking the default behavior when building your non-web apps.

Thus maybe it will be automatically done to font_awesome_flutter or with some minor modifications to this library? :)

**Comment by michaelspiss** [comment]
This is awesome, it basically automates the "hand pick icons you need" step above. From what I understand it should already work with this package as we are using true type fonts. I currently don't have time to test it, but you could yourself: Create a new project, use one icon per style, then compile using 1.19 and 1.20 (using `release` build). The file sizes should differ noticably. If you do, please let me know the results!

**Comment by fzyzcjy** [comment]
Thanks! I will have a look at it. By the way, a tiny suggestion: You may add several sentences in README telling people "you do not need to pay (package size) for what you don't need!" :)

**Comment by michaelspiss** [comment]
Good idea, I'm going to do this once I know if it already works

**Comment by michaelspiss** [comment]
After a little test run it seems like only the material icons (and probably cupertino icons if used) are tree-shaken. Font awesome fonts are untouched in the release apk (flutter 1.20.2, used commands: `flutter build apk`, `flutter build apk --no-tree-shake-icons`).

**Comment by michaelspiss** [comment]
I sadly cannot find anything about what qualifies a font as "icon font", but my best guess is that they are hard coded.

**Comment by fzyzcjy** [comment]
Oh so sad :( maybe I can create an issue in Flutter

**Comment by fzyzcjy** [comment]
Already submitted :)

**Comment by ghowen** [comment]
This might have changed for the better with Flutter 1.22. I now receive errors when building my app as I have a non `const` reference to an FA icon (they are dynamically generated by the icon name that is stored in a database) in code. If I disable tree shaking with `--no-tree-shake-icons` I can build. So the build systems seems to recognize this now for FA icons.

**Comment by michaelspiss** [comment]
Yes, the issue linked above fixed it - this issue is only still open so I won't forget to add a paragraph about it in th readme. Should have clarified that, sorry
