### ISSUE TITLE
Is there a way to get something like the fa-fw class for fixed width

### ISSUE THREAD

**Issue by aktxyz** [fluttercommunity/font_awesome_flutter#118]
like this for the css version

https://fontawesome.com/how-to-use/on-the-web/styling/fixed-width-icons

**Comment by michaelspiss** [comment]
Hi, we do not offer a ready-to-use component for this, but you should be able to achieve the same effect by wrapping the `FaIcon` in an `Align` and `SizedBox` widget:

```
SizedBox(
  width: ...,
  child: Align(
    alignment: Alignment.center,
    child: FaIcon(
      ...
    ),
  ),
)
```

_(Code not tested)_
