### ISSUE TITLE
Duotone stack inversion

### ISSUE THREAD

**Issue by llfbandit** [fluttercommunity/font_awesome_flutter#119]
Using lib in version 8.8.1.

FaDuotoneIcon stack seems inverted. The secondary icon/glyph should be first in stack.
This currently results in inverted colors.

As I'm using an override, here's my fix.

```dart
Stack(
    key: key,
    children: <Widget>[
      FaIcon(
        IconDataDuotone(icon.codePoint + 0x100000),
        size: size,
        color: secondaryColor,
      ),
      FaIcon(
        IconDataDuotone(icon.codePoint),
        size: size,
        color: primaryColor,
      ),
    ],
  )
```

**Comment by michaelspiss** [comment]
I don't know how I missed inverted colors, so thanks for pointing it out! They are however not dependent on their position in the stack. `primaryColor` and `secondaryColor` are inverted. I'm currently a bit short on time, but will create a pull request as soon as possible

**Comment by ghenry** [comment]
I've updated to to 9.10 and my primaryColor colours seems swapped? Maybe I started with 8.8.1. Will check history.

**Comment by ghenry** [comment]
Ah, I was on FA version up until 20 Sep 2020 and just updated to 9.1.0. Will sort. Thanks!
