### ISSUE TITLE
stuck or take too long time flutter run --debug

### ISSUE THREAD

**Issue by gksrb4** [fluttercommunity/font_awesome_flutter#120]
```
[   +2 ms] Updating assets
[ +223 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +12 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:TEST/main.dart b6a90f89-2ea4-42c2-8e82-2a827cacd17a
[        ] <- b6a90f89-2ea4-42c2-8e82-2a827cacd17a
[ +119 ms] Updating files
[+238890 ms] Error writing "build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-brands-400.ttf" to DevFS: HttpException: , uri = http://localhost:55287
[        ] trying again in a few - 9 more attempts left
[ +528 ms] DevFS: Sync finished
[   +1 ms] Synced 2.1MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0x127826e20.
Connecting to VM Service at ws://localhost:55287/ws
```
Hi, I have developed iOS/Android Flutter App.

It sometimes occur this error 
`[+238890 ms] Error writing "build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-brands-400.ttf" to DevFS: HttpException: , uri = http://localhost:55287`.

`font_awesome_flutter: ^8.8.1` I use this.

Could you help about this?

**Comment by michaelspiss** [comment]
I have never seen this message before, sorry. Maybe try a clean install (remove the app from the device and reinstall). What command are you using?

**Comment by gksrb4** [comment]
[Dart-Code/Dart-Code](https://github.com/Dart-Code/Dart-Code/issues/2765#issuecomment-690212504)

It's just like a connection problem If the same error occurs after replacing the cable, I will open the issue again. thanks.

**Comment by gksrb4** [comment]
```
[   +2 ms] Updating assets
[ +216 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +17 ms] Scanning asset files
[   +5 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:MIS/main.dart 47214719-639b-48f2-9f69-a4b6e2285da6
[        ] <- 47214719-639b-48f2-9f69-a4b6e2285da6
[ +136 ms] Updating files
[+238993 ms] Error writing "build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-solid-900.ttf" to DevFS: HttpException: , uri = http://localhost:50153
[        ] trying again in a few - 9 more attempts left
[ +537 ms] DevFS: Sync finished
[   +2 ms] Synced 1.4MB.
[   +2 ms] <- accept
[   +4 ms] Connected to _flutterView/0x10c820420.
Connecting to VM Service at ws://localhost:50153/ws
```
Hi, I have considered [#2765](https://github.com/Dart-Code/Dart-Code/issues/2765#issuecomment-690212504).
so, I changed my cable and disconnected a usb hub.

But, The same error occur somtimes.

I have used vscode and ios device (iphoneX).

 It happens in progress of the same file `build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-solid-900.ttf`.

**Comment by michaelspiss** [comment]
Closing as apparently this is not an issue with this package, but flutter itself (see linked issue above)
