### ISSUE TITLE
Xcode 12, iOS 14, dev channel and tree shaking

### ISSUE THREAD

**Issue by ghenry** [fluttercommunity/font_awesome_flutter#122]
Hi all,

I'm building for iOS 14 and on flutter dev channel hitting this:

```
      ^
    18 warnings generated.
    18 warnings generated.
    This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
      - file:///Users/ghenry/.pub-cache/git/font_awesome_flutter_with_pro_icons-21c4b76f5548070f452b2abd7be244bb94b14bad/lib/src/fa_duotone_icon.dart:58:13
      - file:///Users/ghenry/.pub-cache/git/font_awesome_flutter_with_pro_icons-21c4b76f5548070f452b2abd7be244bb94b14bad/lib/src/fa_duotone_icon.dart:63:13
```

I'm adding this now to resolve, but wondered if anyone has seen this? I may switch back to the beta channel to check too:

`--no-tree-shake-icons`

On latest FA from pub.dev too with pro icons.

Flutter doctor:

```
[✓] Flutter (Channel dev, 1.23.0-4.0.pre, on Mac OS X 10.15.6 19G2021 x86_64, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 3.6)
```

Thanks.

**Comment by edufolly** [comment]
I've got the same problem.

It only occurs on the beta channel.

### Flutter doctor:
```
[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Mac OS X 10.15.7 19H2, locale
    pt-BR)
    • Flutter version 1.22.0-12.2.pre at /Users/edufolly/Documents/flutter
    • Framework revision 2bafdc8226 (4 days ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/edufolly/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/edufolly/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Redmi Note 7 (mobile) • 117d1e8f   • android-arm64  • Android 10 (API 29)
    • Web Server (web)      • web-server • web-javascript • Flutter Tools
    • Chrome (web)          • chrome     • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!
```

**Comment by ghenry** [comment]
It looks like the fix is to just have `const` in these, but haven't had chance to prove that.

**Comment by ghenry** [comment]
I notice you're on Android Studio 4. Have you found any issues with any of the Flutter ecosystem? Sorry, a bit of topic I know.

**Comment by edufolly** [comment]
> It looks like the fix is to just have `const` in these, but haven't had chance to prove that.

Did you've been fork the repo to check your hypothesis? I received an error with Codepoint 62694 in hex 0xf4e6.

I've one suspect:

```
static const IconData fontAwesomeLogoFull = const IconDataRegular(0xf4e6);
static const IconData solidFontAwesomeLogoFull = const IconDataSolid(0xf4e6);
static const IconData brandsFontAwesomeLogoFull = const IconDataBrands(0xf4e6);
```

**Comment by edufolly** [comment]
> I notice you're on Android Studio 4. Have you found any issues with any of the Flutter ecosystem? Sorry, a bit of topic I know.

I haven't had any problems so far. If you have other questions, stay comfortable to send me an email.

**Comment by edufolly** [comment]
> > It looks like the fix is to just have `const` in these, but haven't had chance to prove that.
> 
> Did you've been fork the repo to check your hypothesis? I received an error with Codepoint 62694 in hex 0xf4e6.
> 
> I've one suspect:
> 
> ```
> static const IconData fontAwesomeLogoFull = const IconDataRegular(0xf4e6);
> static const IconData solidFontAwesomeLogoFull = const IconDataSolid(0xf4e6);
> static const IconData brandsFontAwesomeLogoFull = const IconDataBrands(0xf4e6);
> ```

Bullseye! Remove these lines and works like a charm.

**Comment by michaelspiss** [comment]
Hi, sorry for the late reply. Does this still happen in flutter 1.22 stable?

**Comment by ivanjpg** [comment]
I can confirm, still an issue in 1.22 stable.

**Comment by michaelspiss** [comment]
Thanks @ivanjpg, I am going to take a look into this

**Comment by michaelspiss** [comment]
It seems like they added a [full size font awesome text icon](https://fontawesome.com/icons/font-awesome-logo-full?style=brands) which is available as an svg image in `icons.json`, but has no glyph at the given codepoint (?). In `icons.json` it has a unique property `"private": true`, which I guess marks icons not intended for general usage. I'm going to update the generator to honor this.

**Comment by ryon** [comment]
Hi, I'm still seeing the original issue even after updating to the latest Flutter stable and version 8.10.0 of this package. Specifically, I'm seeing that message about non-constant IconData in `fa_duotone_icon.dart`. Disabling the tree-shaking step works around it.

**Comment by michaelspiss** [comment]
Strange, could you copy the error message and check which icons cause this? (The first number after the file path is the icon's line number)

**Comment by ryon** [comment]
Error message:
```
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///Users/runner/work/1/s/lib/packages/font_awesome_flutter-master/lib/src/fa_duotone_icon.dart:58:13
  - file:///Users/runner/work/1/s/lib/packages/font_awesome_flutter-master/lib/src/fa_duotone_icon.dart:63:13
```

The duotone icon I'm trying to use is `FontAwesomeIcons.duotoneHandHoldingUsd`
