### ISSUE TITLE
Multicolor Brand Icons - Google

### ISSUE THREAD

**Issue by JigneshPatel23** [fluttercommunity/font_awesome_flutter#130]
Any help - how can we do this in flutter?

https://stackoverflow.com/questions/52578726/fontawesome-5-multi-color-icon

**Comment by michaelspiss** [comment]
Hi, this is not possible using this package. You may want to use an image or a custom widget for this.

**Comment by AristideVB** [comment]
Still not possible ? : /

**Comment by michaelspiss** [comment]
I probably meant out of the box when I wrote "not possible using this package".

You may be able to achieve what you want by using a shader mask - [example here](https://stackoverflow.com/a/59360135). Icons are essentially nothing more than text.
