### ISSUE TITLE
Clipped icons in Flutter Web

### ISSUE THREAD

**Issue by valentinoguerra** [fluttercommunity/font_awesome_flutter#131]
Some icons are clipped from the right using Flutter Web
To reproduce create an empty proyect and add an icon somewhere, then run or depoly the website.
Try with 'store', 'appleAlt' or 'breadSlice'.

**Comment by michaelspiss** [comment]
Hi, are you using the `FaIcon` widget instead of `Icon`? This should fix the problem

**Comment by valentinoguerra** [comment]
@michaelspiss  Thanks, that was the problem
