### ISSUE TITLE
default size?

### ISSUE THREAD

**Issue by jamesdixon** [fluttercommunity/font_awesome_flutter#135]
Hi, curious if it's possible to set a default size other than created a separate widget that returns an `FaIcon` with the proper size?

**Comment by michaelspiss** [comment]
Hi, sorry for the late reply. If no size is supplied to the `FaIcon` widget, it uses the one set via `IconTheme`. Changing the `size` there will consequently resize all `FaIcon`s as well

**Comment by jamesdixon** [comment]
No need to apologize. Thank you!

**Comment by jamesdixon** [comment]
Hmm I tried this in my theme file like so: `iconTheme: IconThemeData(color: primaryColor, size: 28),` but not seeing any effect. Is this correct?

**Comment by jamesdixon** [comment]
Sorry! It turns out that the icons in question were wrapped in an icon button that was constraining their size 😄
