### ISSUE TITLE
build error due to tree shaking

### ISSUE THREAD

**Issue by jamesdixon** [fluttercommunity/font_awesome_flutter#136]
Hi again,

I'm not sure if this is expected but when I do a release build, I'm seeing an error regarding tree-shaking. I can get around it using `--no-tree-shake-icons` but I wasn't sure if this was an expected issue. Source of the error specifically is: `lib/src/fa_duotone_icon.dart:58:13`

Thanks!

**Comment by michaelspiss** [comment]
Hi, thanks for reporting this. It seems like `FaDuotoneIcon` is missing two `const`s needed for icon tree shaking. I'm currently very short on time, but I will fix this as soon as my schedule allows.

**Comment by michaelspiss** [comment]
It was more of a hassle than I previously thought, but it is finally fixed in version 8.10.2
