### ISSUE TITLE
FontAwesomeIcons Error : Getter not Found: [IconName]

### ISSUE THREAD

**Issue by Tmarks2** [fluttercommunity/font_awesome_flutter#137]
Limited to adobe, fontAwesomeLogoFull, solidFontAwesomeLogoFull, brandsFontAwesomeLogoFull
Launching lib/main.dart on MTFIphone in debug mode...
lib/main.dart:1
Xcode build done.                                           24.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    ../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-2.1.5/lib/IconPicker/Packs/FontAwesome.dart:16:29: Error: Getter not found: 'adobe'.
      'adobe': FontAwesomeIcons.adobe,
                                ^^^^^
    ../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-2.1.5/lib/IconPicker/Packs/FontAwesome.dart:573:43: Error: Getter not found: 'fontAwesomeLogoFull'.
      'fontAwesomeLogoFull': FontAwesomeIcons.fontAwesomeLogoFull,
                                              ^^^^^^^^^^^^^^^^^^^
    ../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-2.1.5/lib/IconPicker/Packs/FontAwesome.dart:574:48: Error: Getter not found: 'solidFontAwesomeLogoFull'.
      'solidFontAwesomeLogoFull': FontAwesomeIcons.solidFontAwesomeLogoFull,
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^
    ../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-2.1.5/lib/IconPicker/Packs/FontAwesome.dart:575:49: Error: Getter not found: 'brandsFontAwesomeLogoFull'.
      'brandsFontAwesomeLogoFull': FontAwesomeIcons.brandsFontAwesomeLogoFull,
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
Could not build the application for the simulator.
Error launching application on MTFIphone.
Exited (sigterm)
tried using different Versions, but still getting error. 
Please Take a look and report any findings

**Comment by Tmarks2** [comment]
I also do not believe that I am currently calling on any of these Icons that is says are erroring out.

**Comment by michaelspiss** [comment]
Hi, this is an error from the flutter_iconpicker package. It seems like their map generator does not ignore icons marked as "private". We fixed this in fluttercommunity/font_awesome_flutter#127. Transferring this issue.
