### ISSUE TITLE
Can not find the './icons.json'

### ISSUE THREAD

**Issue by LiveLikeCounter** [fluttercommunity/font_awesome_flutter#138]
Hi!

I followed the steps in [Apply the pro-icons](https://github.com/fluttercommunity/font_awesome_flutter#how-can-i-use-pro-icons). The problem I face it that the `font_awesome_flutter.dart` isn't updated with the pro-icons, e.g. the [badge-check](https://fontawesome.com/icons/badge-check?style=regular). None of the pro icons are there.

I checked this, because I would like to use a the pro-icons in Flutter like `FaIcon(FontAwesomeIcons.badgeCheck)`.

![image](https://user-images.githubusercontent.com/24720382/101156426-e09e6200-3628-11eb-891f-8bb18d3b3248.png)

On step I didn't execute wat the 
> Move icons.json from metadata to /path/to/your/font_awesome_flutter

because I couldn't find the `metadata` folder.

What did is miss?

Thanks!

**Comment by michaelspiss** [comment]
Hi, the `icons.json` step tells `font_awesome_flutter` about what icons are available - which means this is a crucial step. Running the tool without `icons.json` will replace your font files with the free ones, so you will have to repeat all steps when running the tool again!
The `metadata` folder is on the top level of the font awesome zip you downloaded.

![image](https://user-images.githubusercontent.com/17252710/101157921-2c520b00-362b-11eb-89a3-d934eecfc56a.png)

**Comment by LiveLikeCounter** [comment]
Hi, of course. Now I got it. 
Thanks for you help.
