### ISSUE TITLE
can't find font awesome icons in widget tests

### ISSUE THREAD

**Issue by jamesdixon** [fluttercommunity/font_awesome_flutter#141]
Hello and happy new year!

I ran into an issue when trying to locate Font Awesome Icons in widget tests.

Basically, I have something like:

```
expect(find.byIcon(FontAwesomeIcons.check), findsOneWidget);
```

This returns no widgets. Yet if I replace the font awesome icon in my code with `Icon(Icons.check)` and update my test to use:

```
expect(find.byIcon(FontAwesomeIcons.check), findsOneWidget);
```

...everything works as expected.

Something I'm missing here?

Thank you!

**Comment by michaelspiss** [comment]
Hi, happy new year!

`byIcon` expects flutter's `Icon` class, so it sadly does not work with our  custom `FaIcon`. I suggest you use [byWidgetPredicate](https://api.flutter.dev/flutter/flutter_test/CommonFinders/byWidgetPredicate.html) with `(Widget widget) => widget is FaIcon && widget.icon == FontAwesomeIcons.check` as predicate.

**Comment by jamesdixon** [comment]
@michaelspiss thank you! And also, thank you for pointing me to `byWidgetPredicate` -- that's a new one for me!

Cheers!
