### ISSUE TITLE
Icons not working (web)

### ISSUE THREAD

**Issue by BeliliFahem** [fluttercommunity/font_awesome_flutter#142]
The places where icons should appear becomes boxes on chrome

```
  FaIcon(
    FontAwesomeIcons.userMd,
    size: 50,
  )
```

[RESULT HERE ](https://drive.google.com/file/d/1KCgGJhDp0LsUdDPgBX3iXCdh90IMTzOg/view?usp=sharing)

#### flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on macOS 11.1 20C69 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by shumiyao** [comment]
Do you see  a message like "Could not find a set of Noto fonts to display all missing characters" in console?

Try `--web-renderer=html` option:

```
flutter run -d chrome --web-renderer=html
```

https://github.com/flutter/flutter/issues/76093

**Comment by michaelspiss** [comment]
You may want to run `flutter clean` in your project and do a rebuild. Looks to me like the fonts weren't loaded correctly or this is an issue with flutter itself. I tried to reproduce and everything works as expected, so this is not an issue with this package. You may wanna try @shumiyao's way if the problem persists and if possible.
