### ISSUE TITLE
Crown icon not centered

### ISSUE THREAD

**Issue by sc00n** [fluttercommunity/font_awesome_flutter#149]
When I use the crown Icon, it seems to be shifted to the right when compared to other Icons:

![image](https://user-images.githubusercontent.com/48179232/109981277-0bb85080-7d01-11eb-99bf-158cef41de6e.png)

This is the only Icon where I have this problem (although I tested not ALL of them).

```
      Center(child:
      Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container(
              child: Center(child: Icon(FontAwesomeIcons.crown,color: c,size: totalHeight/1.2,))),

        ]
      )),
```

When I make the Icons smaller, the problem stays the same.

**Comment by michaelspiss** [comment]
Please use `FaIcon` instead of `Icon` as the latter requires all icons to be square - which font awesome icons are not
