### ISSUE TITLE
Pro Icons with Null Safety - update.bat throws error because recase dev dependency doesn't support null safety

### ISSUE THREAD

**Issue by jaredgermano** [fluttercommunity/font_awesome_flutter#151]
Hi there,

I'm trying to upgrade the font awesome library to the null safety pre-release. I downloaded the repository from here: https://github.com/fluttercommunity/font_awesome_flutter/archive/null-safety.zip

After that, I followed the instructions on https://pub.dev/packages/font_awesome_flutter

And when I got to the step to run .\tool\update.bat on windows, I got the following error:

`Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:recase

For solutions, see https://dart.dev/go/unsound-null-safety`

Is there something I'm missing, or it this not ready yet?

Thanks in advance.

**Comment by michaelspiss** [comment]
I updated the dependecy version, please download the null-safety branch again

**Comment by abbadabbatech** [comment]
I have the null safety branch and it still gives same error.  Any thoughts or fixes?

**Comment by michaelspiss** [comment]
Null safety shipped with version 9.0.0 and since uses version 4.0.0 of recase, which supports null safety as well. Please make sure you are using the newest release version (9.1.0) of this package, the null-safety branch is no longer of interest

**Comment by abbadabbatech** [comment]
I am trying to use the process to add pro icons. How does that change the
process?

I have added the fonts and icons.json. When I run the update.bat it fails.
So I downloaded the other branch. So should I be putting something else on
the pubspec?
