### ISSUE TITLE
pub get failed - no lower bound SDK constraint

### ISSUE THREAD

**Issue by coastalgit** [fluttercommunity/font_awesome_flutter#153]
After upgrade to Flutter 2 stable channel, I was unable to build a pro-icon package with version 8.11.0 from master,  getting error when running `flutter packages get`:

```
pubspec.yaml has no lower-bound SDK constraint.
You should edit pubspec.yaml to contain an SDK constraint:

environment:
  sdk: '>=2.10.0 <3.0.0'
```

**Comment by droidzone** [comment]
Starring this.

**Comment by coastalgit** [comment]
Thanks @droidzone -  that resolved pub get.
