### ISSUE TITLE
Error while updating to pro icons 

### ISSUE THREAD

**Issue by drmspatil** [fluttercommunity/font_awesome_flutter#155]
This is in powershell.

Updating free icons to newest version.
The system cannot find the path specified.
Error when reading '.\tool\generate_font.dart': No such file or directory.
Error when reading '.\tool\generate_example.dart': No such file or directory.
No file or directory found at ".\lib\font_awesome_flutter.dart".
No file or directory found at ".\example\lib\icons.dart".

**Comment by michaelspiss** [comment]
Are you running the script from the projects root folder? Please make sure to run `tool\update.bat` and **not only** `update.bat` **from inside** the tool folder. I guess I should update the script to not be reliant on that though...

**Comment by drmspatil** [comment]
It worked . thanks

**Comment by michaelspiss** [comment]
Your may need to run `flutter clean` and do a rebuuld after that. Flutter sometimes has problems with updating assets.

**Comment by drmspatil** [comment]
Tried it but not working . Even tried to use as local package and as a integrated code also but not happening. Could it be generation issue ?

**Comment by michaelspiss** [comment]
You may also need to reinstall the app. I've tested the generator script with the last couple of fimt awesome versions without problems, so I'm fairly certain this is just an asset update bug.

**Comment by drmspatil** [comment]
With some tweaks its working now . Thanks . I am using duotone icons  `   FaDuotoneIcon(
                  FontAwesomeIcons.duotoneAirplay,
                  size: 50,
                  primaryColor: Colors.black,
                  secondaryColor: Colors.amber,
                )`
Getting error: The argument type 'IconData' can't be assigned to the parameter type 'IconDataDuotone'.

when used in FaIcon() same duotone icon works fine . However it doesn't work with FaDuotoneIcon().

**Comment by michaelspiss** [comment]
Good to hear it's working now.
The duotone icon bug is tracked at #154, I'll have a look at it later today.

**Comment by michaelspiss** [comment]
Could you do me a favor and describe your problem again in the issue linked above?
I cannot replicate any errors with duotone icons
