### ISSUE TITLE
New Pro pack alpha `search` => `magnifying-glass`

### ISSUE THREAD

**Issue by amkuchta** [fluttercommunity/font_awesome_flutter#159]
Although this may not be an issue yet, the v6 alpha also changes `search` to `magnifying-glass`; this will need to be updated in the example app, as `search` no longer resolves properly.

**Comment by michaelspiss** [comment]
Thank you so much for bringing this to my attention! Changed icon names probably warrant a new major version as well, as the pacckage is no longer fully backwards compatible to version 5 icons.

**Comment by stedekay** [comment]
I upgraded font_awesome_flutter to the current release (9.1.0) and had a lot of renamings (like search, commentAlt, calendarAlt, etc.)
All these icon names are aliases in the icons.json.
I don't know if they were aliases before but it seems that it would be helpful when your package can also handle the aliases.

**Comment by michaelspiss** [comment]
I added aliases to version 10, marked them all as `@Deprecated` however.
The decision to mark them as such is based on the uncertainty, of whether aliases are here to stay or if they are solely for the purpose of making the transition to version 6 easier.
It should also guide users towards the new icon names, as the deprecation notice also shows the new icon name.
