### ISSUE TITLE
Duotone icones not showing on android in release mode

### ISSUE THREAD

**Issue by RegisSaffi** [fluttercommunity/font_awesome_flutter#164]
I have been developing the app, I am using pro Duotone icons by overriding dependency in my `pubspec.yaml` as described in the documentation.

 Duotone icons are showing perfectly on android emulator and iOS simulator (debug versions) even on real device in debug mode, but they are not showing in release mode, they just appear as boxes (refer to below image)

I only tested this release mode on android, I am not sure how it is reacting on iOS.

I also tested it on web, it works perfectly in both debug and release, but some icons doesn't show when using  web on mobile, I am not sure why.

NB: This is only happening on DuoTone icons, others like solid,light,regular or thin are showing perfectly (the ones I tested)

Anyone had this issue before? Below there is reference image on how they are showing!

[Screenshot_2021-04-27-01-48-20-18_0a3832b975ffcf1722fc2aeec1acafdd.jpg](https://user-images.githubusercontent.com/37751670/116166911-5baf0480-a6ff-11eb-91a0-4976ddf7c88e.jpg)

**Comment by AliYar-Khan** [comment]
Same thing happening to me. Icons didn't display properly

**Comment by RegisSaffi** [comment]
@AliYar-Khan I realized it only happens if you build release with `flutter run build` , you will have to build release by opening android module in android studio and generate release as you do in normal Android project.

**Comment by michaelspiss** [comment]
Hi, sorry for the late reply.
Running `flutter clean` in your project and then building again should fix your problem.
