### ISSUE TITLE
Some free icons are missing

### ISSUE THREAD

**Issue by guyluz11** [fluttercommunity/font_awesome_flutter#166]
Not sure why but some of the free icons are missing from the package.

For example [`thermometer-half`](https://fontawesome.com/icons?d=gallery&p=2&q=temprature&m=free)
![image](https://user-images.githubusercontent.com/9304740/119278506-5ecddf80-bc2e-11eb-81fe-b403b5185701.png)

![image](https://user-images.githubusercontent.com/9304740/119278447-ff6fcf80-bc2d-11eb-93dc-47cf926e2427.png)

This is not the first time that icons are missing, should I report each time or is it deliberately.

Version: `font_awesome_flutter: ^9.0.0`

**Comment by michaelspiss** [comment]
Hi, thanks for noticing! This is definitely not on purpose. If there are more icons missing, please don't hesitate to comment here. I will look into this soon

**Comment by guyluz11** [comment]
My bead,
One is called `temperature` and one is called `thermometer`.
It is working, thanks.
