### ISSUE TITLE
Why Dont Have sign-in Icon?

### ISSUE THREAD

**Issue by CyberDepot** [fluttercommunity/font_awesome_flutter#167]
hi
im usin the pro version of font awesome on my project
but dont have any sign-in or signIn (cammel case) icon in my project!

i do "How can I use pro icons" step by step
my os is windows 10 pro

**Comment by michaelspiss** [comment]
Hi, please make sure you have at least font awesome pro 5.0.0 (i think this was when this icon was introduced). To make sure, open your `icons.json` and search for `sign-in`.

Also, please check that other pro icons are there. Otherwise, it may be that the upgrade process failed completely.
