### ISSUE TITLE
Icons.json not available in zip provided for integrating pro icons

### ISSUE THREAD

**Issue by LuciferAJ** [fluttercommunity/font_awesome_flutter#185]
### Font awesome pro icons 6:
**Plugin: [Font Awesome](https://pub.dev/packages/font_awesome_flutter) 9.2.0**

The downloaded zip for pro icons of Font Awesome didn't have a metadata folder in it, and due to which cannot find icons.json. 

I have followed the instructions given in [here](https://pub.dev/packages/font_awesome_flutter#setup), But according to that there must be a metadata folder that contains icons.json for the configurator.sh to execute, Is the implementation has been changed.

Please let me know regarding how to implement font awesome pro icons 6.

I have attached a screenshot of the files after extracting the zip

<img width="300" alt="Screenshot 2021-10-28 at 12 46 52 PM" src="https://user-images.githubusercontent.com/25266736/139205908-34849bc0-7f59-4c77-b1ab-6f9cfa99c695.png">

**Comment by daniel-hopkins** [comment]
any news on this. I just bought V6 pro today not knowing it wasn't compatible with Flutter
