### ISSUE TITLE
a missing icon

### ISSUE THREAD

**Issue by viniciusddrft** [fluttercommunity/font_awesome_flutter#193]
Hi, the project is very good and I always use it, but I think that an icon that doesn't have and is needed is the one below, I searched a lot and saw that there really isn't anything like this one.

![sun-and-moon-4452](https://user-images.githubusercontent.com/50067152/147417360-da47901b-2029-4cd9-bc74-01ba23fb4fc0.png)

**Comment by michaelspiss** [comment]
Hi @viniciusddrft! We are not the official font awesome team, but only port their icons to be usable with flutter. If you have icon recommendations, please contact font awesome directly via [their website](https://https://fontawesome.com)/.
