### ISSUE TITLE
Icons not showing properly

### ISSUE THREAD

**Issue by MarsadMaqsood** [fluttercommunity/font_awesome_flutter#194]
Icons not showing/rendering ... properly
pub version
```yaml
font_awesome_flutter: ^9.2.0
```
Flutter 2.8.1

```dart
       Row(
         children: [
           FaIcon(FontAwesomeIcons.facebook),
           FaIcon(FontAwesomeIcons.google),
           FaIcon(FontAwesomeIcons.whatsapp),
         ],
       ),
```

<img height="600" src="https://i.imgur.com/c20FP9u.jpg"/>

**Comment by michaelspiss** [comment]
Looks like flutter has not updated its assets yet. Try running `flutter clean` in your project and then rebuild
