### ISSUE TITLE
initial load size

### ISSUE THREAD

**Issue by gururaja-kambala** [fluttercommunity/font_awesome_flutter#196]
I am trying to use font awesome in flutter web

after adding  font_awesome_flutter: ^9.2.0 in pubspec.yml 

If I check Network tab in chrome dev tool, i could see below 3 files getting loaded. One of them is 8 MB, is it mandatory dependency for font awesome? can we reduce files size if we need only selected icons?

![image](https://user-images.githubusercontent.com/66516393/149661512-0836a8d2-1870-4814-9e5c-6bd7d6297d85.png)

full url for this 8mb file is 
https://fonts.gstatic.com/s/notocoloremojicompat/v38/TUZgzxRkpOVJnwykwd_mLYH3Fv9u9SaFlBEYPRbQ.woff2

**Comment by gururaja-kambala** [comment]
flutter is downloading this file, only if I run package by "flutter run"

If I build package using "flutter build web" and then deploy package in web server it works great.

**Comment by michaelspiss** [comment]
Hi, I'm not sure why flutter does this, but we neither have a dependency on nor an import of any google emojis.
You may want to ask the flutter dev team why this happens, but I guess it's for development compatability reasons.
However, I don't see the problem as long as it's not in the release build.
