### ISSUE TITLE
Member not found: 'tripadvisor'. 'tripadvisor': FontAwesomeIcons.tripadvisor, 

### ISSUE THREAD

**Issue by roldanunne** [fluttercommunity/font_awesome_flutter#197]
Member not found: 'tripadvisor'. 'tripadvisor': FontAwesomeIcons.tripadvisor, 

I experience this error in 9.2.0

**Comment by michaelspiss** [comment]
Font awesome removed the tripadvisor icon as per tripadvisor's request in version 5.15.4 (see #187).
