### ISSUE TITLE
Update to Font Awesome Version 6

### ISSUE THREAD

**Issue by devj3ns** [fluttercommunity/font_awesome_flutter#199]
[Font Awesome Version 6 is released](https://blog.fontawesome.com/font-awesome-6-2/) 🎉

**Comment by michaelspiss** [comment]
Hi! Whilst I'm also excited for the new icons, it will take a while until they are going to be available for flutter.
Font awesome have removed the metadata folder, which we use to generate the flutter/icon bindings. However, they currently consider re-adding it.

Until their decision is final, this package will not be updated and stays at the current version. I simply don't have the time to rewrite the generator again, to support their GraphQL API and all its future iterations.

If you'd like to see font awesome 6 icons in flutter anytime soon, I suggest you drop them an email regarding the missing metadata folder in fa6.

**Comment by ryanawhelan** [comment]
@devj3ns I am using 6.0, if you want to give it a try:
https://github.com/ryanawhelan/font_awesome_flutter

**Comment by 3ph** [comment]
From FontAwesome team today:

`Our dev team is currently working on that. I don't have a release date just yet, but we will get the word out when it's ready.`

**Comment by chrisjones314** [comment]
FWIW, I have been subscribing to FA for a few years, and I emailed support about this issue.  I got an email back stating "Thanks for reaching out. We are actually releasing that this week. Stay tuned!"  I got that email on March 14th.   So, hopefully that indicates something is happening, perhaps that they are just adding the icons.json back.

**Comment by chrisjones314** [comment]
The icons.json works, but it contains two icons that are named with numbers (00 and 42something).   These aren't valid identifiers.  Its easy to work around, which I did successfully and it is now working, but out of the box it yields compilation errors in the generated .dart files.

**Comment by devj3ns** [comment]
Thanks for your work @michaelspiss 💙
