### ISSUE TITLE
Can't be assigned to the parameter type 'Icon'

### ISSUE THREAD

**Issue by dhust** [fluttercommunity/font_awesome_flutter#204]
I'm trying to use `font_awesome_flutter: ^9.2.0` along with `icon: const FaIcon(FontAwesomeIcons.gamepad)` but I get the error `The argument type 'FaIcon' can't be assigned to the parameter type 'Icon'.` I'm using it with `HawkFabMenuItem` which has an attribute of `{required Icon icon}` so it seems to be like most icon attributes, but it gives me an error. Thoughts on why?

**Comment by michaelspiss** [comment]
Closing, as there is nothing we can do about it until the issue above is fixed.
