### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Zazo032** [fluttercommunity/font_awesome_flutter#205]
Seems like the library is using an outdated version of FA, some icons have naming inconsistencies (they were probably renamed on FA side, but not re-generated on the plugin), and some icons (like `pen-to-square` are missing)

**Comment by michaelspiss** [comment]
Hi, the stable version published on pub.dev is still on 5.12.4, as Font awesome didn't provide a file we needed to generate the code for version 6.0.0. However, 6.1.0 came out yesterday and it includes this file again. The update is nearly finished, it's just missing some fine tuning - so expect the update to be public within the next 24-48 hours.
