### ISSUE TITLE
Error running configurator.sh with pro icons on v10.0.0 (regular 100 icon)

### ISSUE THREAD

**Issue by samry** [fluttercommunity/font_awesome_flutter#206]
There seems to be an error with version 10.0.0 and the configurator.sh when pro icons are enabled.

In particular, the hundredPoints / 100 "regular" icon.

When running configurator.sh with no exclusions, the following error occurs:

```
line 36513, column 14 of lib/font_awesome_flutter.dart: Expected to find ';'.
    
36513 │ static const IconData 100 = hundredPoints;
```

Just manually changing it to 'static const IconData regular100 = hundredPoints;' in 'font_awesome_flutter.dart' works as a quick fix, but just wanted to submit this issue in case anyone else was running into this.

**Comment by michaelspiss** [comment]
Thanks for reporting. Should be fixed by 96ea35a.
