### ISSUE TITLE
icons of fontawsome 6.0 and above missing

### ISSUE THREAD

**Issue by efinder2** [fluttercommunity/font_awesome_flutter#212]
Icons like cards-blank,
cloth-hanger,
...

**Comment by michaelspiss** [comment]
The website says these are pro icons. You can only use them if you have a font awesome pro license and followed the instructions to enable them in font_awesome_flutter.

**Comment by brianegan** [comment]
I'm updating the README @michaelspiss haha, peeps keep missing this :)

**Comment by michaelspiss** [comment]
I just wanted to add an issue template for "missing icon", the new font awesome website really does not do a good job differentiating between free/pro icons..

**Comment by brianegan** [comment]
Yah, I was thinking the same. Added one of those as well :)

**Comment by efinder2** [comment]
overlooked that on their page. sorry

**Comment by michaelspiss** [comment]
Don't worry, this happened a lot lately
