### ISSUE TITLE
Activate Pro icons in the web version

### ISSUE THREAD

**Issue by bahiraei** [fluttercommunity/font_awesome_flutter#218]
Hi, I tried to add Pro icons to the web flutter version, but I could not.

**Comment by michaelspiss** [comment]
Hi, we're gonna need a bit more information to help you. What have you tried? What does not work? Is there an error message? What version of flutter do you use?

**Comment by michaelspiss** [comment]
Closing because there hasn't been an answer for over a month. If you still have this problem, feel free to reopen this or create another issue.
