### ISSUE TITLE
Dependency_overrides path seems ambiguous

### ISSUE THREAD

**Issue by Eugeniegrandit** [fluttercommunity/font_awesome_flutter#220]
**Describe the bug**

Path in dependency_overrides seems ambiguous.
It's not a bug, more a suggestion.

**To Reproduce**

Following the setup:

dependency_overrides:
  font_awesome_flutter:
    path: /path/to/your/font_awesome_flutter

I tried:

dependency_overrides:
  font_awesome_flutter:
    path: /dependencies/font_awesome_flutter

I got:

pub get failed (66; Because myApp depends on font_awesome_flutter from path which doesn't exist (could not find package font_awesome_flutter at "/dependencies/font_awesome_flutter"), version solving failed.)

I tried:

dependency_overrides:
  font_awesome_flutter:
    path: dependencies/font_awesome_flutter

It worked.

**Expected behavior**

I suggest modifying the path in the Readme from:

dependency_overrides:
  font_awesome_flutter:
    path: /path/to/your/font_awesome_flutter

to:

dependency_overrides:
  font_awesome_flutter:
    path: path/to/your/font_awesome_flutter

Hope it helps, thanks for this wonderful package!

**Comment by michaelspiss** [comment]
I love these kinds of proposals which aim to make stuff more beginner friendly. I can absolutely see how the first `/` might confuse people. Thanks for your help!
