### ISSUE TITLE
Kindly update the Plugin to Font Awesome 6.1.2 version

### ISSUE THREAD

**Issue by jinosh05** [fluttercommunity/font_awesome_flutter#222]
Before submitting this issue, please double-check if the icon is a pro icon on the Font Awesome website. It will say something like "Start using this pro icon."

This package only includes the free icons by default. To use pro icons, you must purchase a license and follow the instructions found in the README.md file.

**Comment by michaelspiss** [comment]
Updated straight to 6.2.0 in release 10.2.0

**Comment by jinosh05** [comment]
Thanks for updating the package
