### ISSUE TITLE
[Lint} isAlwaysShown property is deprecated, suggest replace with thumbVisibility

### ISSUE THREAD

**Issue by saropa** [fluttercommunity/font_awesome_flutter#227]
Hi, thank you so much for this package!

I found a simple lint issue in the Scrollbar:
```
'isAlwaysShown' is deprecated and shouldn't be used. Use thumbVisibility instead.
```

main.dart # 50, suggest changing
``` isAlwaysShown: kIsWeb, ```

to
``` thumbVisibility: kIsWeb, ```

**Comment by michaelspiss** [comment]
Thanks for pointing this out. I'm going to update this in the next release
