### ISSUE TITLE
Flutter Build Option `--tree-shake-icons` fails due to font_awesome_flutter-10.2.1

### ISSUE THREAD

**Issue by churchianity** [fluttercommunity/font_awesome_flutter#228]
If you build a flutter application with the option `--tree-shake-icons` for the web, you get some errors coming from `icon_data.dart`. Tree shaking only works for icon data that is `const`, and a few `IconData` subclasses introduced by `font_awesome_flutter` are not considered `const`.

- build a flutter 3.3.9 application using `font_awesome_flutter` (version 10.2.1) with the option `--tree-shake-icons` enabled
- observe the output

**Expected behavior**
To be fair, it's not necessarily a 'bug', but being able to tree shake icons is very valuable for minimizing bundle size, and many people will likely be serving more icons that they need to while this behavior exists.

**Screenshots**
![image](https://user-images.githubusercontent.com/43279719/206765107-21dff8ce-ccdc-4464-a8bd-279f6baf9f5e.png)

**Desktop (please complete the following information):**
 - OS: Tested on Windows 10 and MacOSX Catalina - appears on both
 - font_awesome_flutter version 10.2.1
 
 **Additional Information**
 I understand that having a dynamic type may be built into the assumptions of this codebase, and difficult to remove. If that's the case, feel free to close this.

**Comment by michaelspiss** [comment]
Thanks for reporting this. It would be a bug, as we officially support icon tree shaking. However, I cannot reproduce this.
The [specified lines](https://github.com/fluttercommunity/font_awesome_flutter/blob/master/lib/src/icon_data.dart) also all contain a const call, so I cannot see how there would be an error.

Building the example app runs without errors (tree shaking is enabled by default):
```
C:\Users\Michael\IdeaProjects\font_awesome_flutter\example>flutter build apk

 Building with sound null safety

Calling mockable JAR artifact transform to create file: C:\Users\Michael\.gradle\caches\transforms-2\files-2.1\43bf54ced26cecd29a682cf452e6d9a2\android.jar with input C:\Users\Michael\AppData\Local\Android\sdk\platforms\android-28\android.jar
Removed unused resources: Binary resource data reduced from 47KB to 38KB: Removed 19%
Running Gradle task 'assembleRelease'...                          238.8s
√  Built build\app\outputs\flutter-apk\app-release.apk (18.3MB).
```

This is an odd one, especially since it happens on two separate machines. Could you please attach the output of `flutter doctor -v` and maybe run `flutter clean` and `flutter pub get` again, to make sure this is not some cached old version?

**Comment by churchianity** [comment]
![image](https://user-images.githubusercontent.com/43279719/206862859-bd19b065-ad30-415a-af88-76f5ef1bd0b0.png)

![image](https://user-images.githubusercontent.com/43279719/206863170-e474f82c-b4c4-48db-980a-619826df3282.png)

No dice, it seems. I can try and make a minimally reproducible example, but that might be a challenge.

**Comment by churchianity** [comment]
> Thanks for reporting this. It would be a bug, as we officially support icon tree shaking. However, I cannot reproduce this. The [specified lines](https://github.com/fluttercommunity/font_awesome_flutter/blob/master/lib/src/icon_data.dart) also all contain a const call, so I cannot see how there would be an error.
> 
> Building the example app runs without errors (tree shaking is enabled by default):
> 
> ```
> C:\Users\Michael\IdeaProjects\font_awesome_flutter\example>flutter build apk
> 
>  Building with sound null safety
> 
> Calling mockable JAR artifact transform to create file: C:\Users\Michael\.gradle\caches\transforms-2\files-2.1\43bf54ced26cecd29a682cf452e6d9a2\android.jar with input C:\Users\Michael\AppData\Local\Android\sdk\platforms\android-28\android.jar
> Removed unused resources: Binary resource data reduced from 47KB to 38KB: Removed 19%
> Running Gradle task 'assembleRelease'...                          238.8s
> √  Built build\app\outputs\flutter-apk\app-release.apk (18.3MB).
> ```
> 
> This is an odd one, especially since it happens on two separate machines. Could you please attach the output of `flutter doctor -v` and maybe run `flutter clean` and `flutter pub get` again, to make sure this is not some cached old version?

Isn't the `codepoint` argument not being const the culprit here?

**Comment by michaelspiss** [comment]
Can you try building the example app?
To do this, clone this repository and go to the example subfolder. Then run `flutter pub get` and `flutter build`

**Comment by churchianity** [comment]
Is there a reason why I'd need to build the `apk` specifically? I'm only really targeting the web at the moment, and I don't have a java installation to build with the apk right. If it's necessary I could get it.

Running `flutter build web` in the example directory works. However, if I run `flutter build web --tree-shake-icons` in the example directory, it does not work, and I get a message consistent with what I had before:


![image](https://user-images.githubusercontent.com/43279719/207080612-0cf44077-9988-4206-ae2c-a3de1689afc7.png)

**Comment by michaelspiss** [comment]
Icon tree shaking is disabled for web builds - so adding "--tree-shake-icons" breaks your build. This is an [open issue of the flutter framework](https://github.com/flutter/flutter/issues/57181).

**Comment by churchianity** [comment]
My apologies. Thanks for the link. I feel a bit misled that the option doesn't spit out 'not supported', but that is certainly not your problem. 

Thanks for the help.

**Comment by michaelspiss** [comment]
No worries, I wasn't aware of this limitation either. I would have expected an error message as well. Good luck with your project!

**Comment by churchianity** [comment]
With flutter 3.3.10, they added the ability to tree shake fonts from web builds, with the normal flag of `--tree-shake-icons`. 

You can see it in the notes here: https://github.com/flutter/packages/commit/13fb549af668ff8957eef526573756eff4ef42ab

And the specific issue: https://github.com/flutter/flutter/pull/115886

![image](https://user-images.githubusercontent.com/43279719/208187714-3a9a145b-f75c-4a19-9a61-a387eb521994.png)

I got the same stuff I got before it was even supported... a bit mysterious.

**Comment by michaelspiss** [comment]
Flutter 3.3.10 is not released yet, the latest stable version is 3.3.9.
If you want to use upcoming features, switch to the beta branch first.

I'd personally just wait for flutter 3.3.10 to release, so they can figure out the quirks first and you don't end up with an unstable system though.

**Comment by churchianity** [comment]
![image](https://user-images.githubusercontent.com/43279719/208250797-b366c67c-2d5e-4632-b12e-75b18ad72335.png)

I may be confused, but I'm on the stable channel, and have version 3.3.10

**Comment by michaelspiss** [comment]
Ah so they just haven't updated the web docs then - that's where I looked as I currently don't have access to a PC.
Are you sure web icon tree shaking is included in 3.3.10? It would be kinda strange to have a feature added in a Bugfix release and I cannot find anything about it in the [release notes](https://github.com/flutter/flutter/releases/tag/3.3.10). I'd assume web icon tree shaking to be available with 3.4.0 if it has already been merged.

**Comment by churchianity** [comment]
Yeah, my mistake after all (again). 

![image](https://user-images.githubusercontent.com/43279719/211126130-bcb6d3a0-0e17-47c2-a596-d45774dac136.png)

It appears to be planned for `3.7`.

**Comment by michaelspiss** [comment]
Thanks for the research though, those are great news for the future!

**Comment by michaelspiss** [comment]
No, sorry
