### ISSUE TITLE
Custom web fonts is missing

### ISSUE THREAD

**Issue by jackwill99** [fluttercommunity/font_awesome_flutter#230]
I'm using pro version and also have custom web fonts. But there is missing custom web fonts icon...

**Comment by michaelspiss** [comment]
Hi!
Sorry, I'm going to need a bit more info than that to really help you. Which icon is missing for you? Which versions are you using? Does the icon exist on https://fontawesome.com/search? Otherwise it may have been removed.

**Comment by codingiswhyicry** [comment]
Not OP, but I'm experiencing this issue too after having custom icons working and I'm not using this package. I'm thinking it might be a flutter issue, just wanted to add this comment in case it was helpful in the future. 

I used font awesome to make a custom font asset file, and none of the icons are rendering. It's been tested in debug and release mode, and even when built for web, it just displays placeholder image.

**Comment by michaelspiss** [comment]
Thanks @codingiswhyicry for your feedback. It seems like this is an issue with font awesome custom icons. Maybe they internally rearrange glyphs so they no longer show up using font_awesome_flutter. Another option could be that flutter cannot render the custom icon's format.

No matter what, custom icons are not something this package officially supports, as it is a pro-only feature. You may get them to work - and if you do please let me know how - but I have no plans on working on this.
