### ISSUE TITLE
WhatsApp icon not supporting in Flutter version 3.3.10

### ISSUE THREAD

**Issue by Rafi404** [fluttercommunity/font_awesome_flutter#232]
WhatsApp icon not supporting in Flutter version 3.3.10

It Shows the message, The getter 'whatsapp' isn't defined for the type 'Icons'.

**Comment by razfazz** [comment]
FaIcon(FontAwesomeIcons.whatsapp) this also stopped working and showing a blank icon

**Comment by zogol** [comment]
same here. whatsapp icon is gone in the fontawesome package

**Comment by michaelspiss** [comment]
I could not reproduce, but the new version was just released and I made sure it has the whatsapp icon. Please try if updating the package fixes your issues.
