### ISSUE TITLE
How to use Pro version?

### ISSUE THREAD

**Issue by BeiAduo** [fluttercommunity/font_awesome_flutter#233]
I followed the tutorial and it worked; but I don't know how to use it in my new project?

**Comment by Rafi404** [comment]
Which is your Flutter Version?

**Comment by BeiAduo** [comment]
last Version

**Comment by Rafi404** [comment]
Add font_awesome_flutter: ^10.3.0 package in pubspec.yaml file. Then use like this

 FaIcon(
           Icons.access_alarm,
           color: whatsappColor,
           size: 30,
          ),

**Comment by michaelspiss** [comment]
If you haven't updated your package override, please have a look at the custom package [setup](https://github.com/fluttercommunity/font_awesome_flutter#setup) doc.
Then use the icons like @Rafi404 already presented. A more complete example is also available in the [usage](https://github.com/fluttercommunity/font_awesome_flutter#usage) section.

If there are any specific issues, don't hesitate to ask, but it might take me a while to answer.

**Comment by michaelspiss** [comment]
You should have something like `font_awesome_flutter: ^10.3.0` in your `pubspec.yaml`. This, however, refers to the version on pub.dev.  To link to your custom copy which includes pro icons, add the following lines:
```
dependency_overrides:
  font_awesome_flutter:
    path: path/to/your/font_awesome_flutter
```
Replace `path/to/your/font_awesome_flutter` with the file path to your custom version on your system.

Other than that, use it just like the normal version.

**Comment by BeiAduo** [comment]
Thanks
