### ISSUE TITLE
./configurator.sh: command not found

### ISSUE THREAD

**Issue by NTMS2017** [fluttercommunity/font_awesome_flutter#234]
```
********@******-MBP util % sudo ./configurator.sh
Password:
sudo: ./configurator.sh: command not found
```

I goto cd util and try to run configurator.sh but I got command not found error. Any idea?

**Comment by michaelspiss** [comment]
Hi, there are several things you can try.
1. In the util directory, run `chmod +x configurator.sh`
2. Replace the first line in configurator.sh with `#!/bin/bash`
3. Add a newline to configurator.sh

Can you try and if, report back what worked?

**Comment by AristideVB** [comment]
> Hi, there are several things you can try.
> 
> 1. In the util directory, run `chmod +x configurator.sh`
> 2. Replace the first line in configurator.sh with `#!/bin/bash`
> 3. Add a newline to configurator.sh
> 
> Can you try and if, report back what worked?

Thanks, running ./configurator.sh after your 3 steps worked for me

**Comment by michaelspiss** [comment]
Thanks for the feedback!
