### ISSUE TITLE
Not generating icons.dart file

### ISSUE THREAD

**Issue by bharathkandula99** [fluttercommunity/font_awesome_flutter#238]
I inserted 'font awesome flutter: 10.4.0' to my project file and executed the 'flutter pub get' command.
`icons
        .where((icon) =>
            _searchTerm.isEmpty ||
            icon.title.toLowerCase().contains(_searchTerm.toLowerCase()))
        .toList();`

The above code was provided to obtain a filtered icons list, however I am unable to locate my project's 'icons. dart' file.
Should I manually include the 'icons.dart' file or will it be generated?

But, in git, the [icons.dart](https://github.com/fluttercommunity/font_awesome_flutter/blob/master/example/lib/icons.dart) file should be automatically generated.

**Comment by michaelspiss** [comment]
Hi, the icons.dart file is only created for the example app and not exported for general use by the package to allow release optimizations. You can obtain a similar list by reading the [customizing font awesome flutter](https://github.com/fluttercommunity/font_awesome_flutter#customizing-font-awesome-flutter) steps and more importantly following the steps to [retrieve icons dynamically](https://github.com/fluttercommunity/font_awesome_flutter#retrieve-icons-dynamically-by-their-name-or-css-class). Please be aware that this is going to impact the resulting bundle size.
