### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by patolax** [fluttercommunity/font_awesome_flutter#241]
I can't find these icons. Are they missing or am I doing it wrong?
The downloaded ttf file from this reop does not have them either. 

https://fontawesome.com/search?q=boxing&o=r

**Comment by michaelspiss** [comment]
Hi @patolax! The icons you mentioned seem to be pro icons. You need to buy a pro license and follow the readme's steps to activate them.

Thanks @saropa as well - seems like an update is due

**Comment by saropa** [comment]
> Hi @patolax! The icons you mentioned seem to be pro icons. You need to buy a pro license and follow the readme's steps to activate them.
> 
> Thanks @saropa as well - seems like an update is due

Just want to say a quick off-topic thank you for the fantastic package! (and an update to 6.4 can be put to use right away!)

**Comment by michaelspiss** [comment]
Thanks, much appreciated!

**Comment by michaelspiss** [comment]
I just updated the version to use font awesome 6.4, feel free to update!
