### ISSUE TITLE
Can we reduce file size as flutter did for material icons

### ISSUE THREAD

**Issue by chetanxpatil** [fluttercommunity/font_awesome_flutter#242]
<img width="1440" alt="Screenshot 2023-05-23 at 5 23 40 AM" src="https://github.com/fluttercommunity/font_awesome_flutter/assets/71105582/5da8a995-9b45-470f-93a0-77f1e747336a">
That would be great if its possible to reduce size.

**Comment by michaelspiss** [comment]
This package already supports this feature. However, flutter does not perform tree shaking for web builds yet. As far as I know, it is still being worked on.
