### ISSUE TITLE
Unfortunately we need now a new twitter icon

### ISSUE THREAD

**Issue by klaussk8** [fluttercommunity/font_awesome_flutter#248]
I don't know if font awesome already have the new Twitter icon, but who need the Twitter icon, like me, can wait until it will be available here...

Thanks for this awesome library

**Comment by andychucs** [comment]
I hav updated at https://github.com/fluttercommunity/font_awesome_flutter/pull/250
If you want it immediately, just clone this branch.

**Comment by michaelspiss** [comment]
Fixed with #250
