### ISSUE TITLE
FontAwesomeIcons.clone and FontAwesomeIcons.solidClone are inconsistent with the following link

### ISSUE THREAD

**Issue by ddxl123** [fluttercommunity/font_awesome_flutter#249]
FontAwesomeIcons.clone and FontAwesomeIcons.solidClone are inconsistent with the following link:
solid and regular
https://fontawesome.com/icons/clone?f=classic&s=solid
https://fontawesome.com/icons/clone?f=classic&s=regular

**Comment by michaelspiss** [comment]
Maybe there was an update to the icons with a newer font awesome version. They look the same as in the link with font awesome version 6.4.2.
