### ISSUE TITLE
Tree shaking requires @staticIconProvider annotation

### ISSUE THREAD

**Issue by ltOgt** [fluttercommunity/font_awesome_flutter#253]
Had an issue where Font awesome icons were not reduced by tree shaking:

![image](https://github.com/fluttercommunity/font_awesome_flutter/assets/24209580/579bb23c-237c-43e8-8278-4331ce8f9850)

Turns out you need to add the `@staticIconProvider` annotation

Compare
- flutters `Icons` with annotation: https://github.com/flutter/flutter/blob/e1e47221e86272429674bec4f1bd36acc4fc7b77/packages/flutter/lib/src/material/icons.dart#L153
- font awesomes `FontAwesomeIcons` without annotation: https://github.com/fluttercommunity/font_awesome_flutter/blob/32beff2ea1156d62d0c2130b8202b88a9724508f/lib/font_awesome_flutter.dart#L11

___
https://github.com/fluttercommunity/font_awesome_flutter/blob/32beff2ea1156d62d0c2130b8202b88a9724508f/util/lib/main.dart#L345

**Comment by michaelspiss** [comment]
Hey @ltOgt, hanks for bringing this up! `@staticIconProvider` will be available with the next release
