### ISSUE TITLE
FaIcon size 24

### ISSUE THREAD

**Issue by vasilich6107** [fluttercommunity/font_awesome_flutter#254]
**Describe the bug**
How to make icon take no more than 24 px by longest side?

**To Reproduce**
```
        SizedBox.square(
          dimension: 24,
          child: const FaIcon(
            FontAwesomeIcons.building,
            size: 24,
          ),
        )
```

**Expected behavior**
The icon should be no more than specified size

**Screenshots**
<img width="46" alt="image" src="https://github.com/fluttercommunity/font_awesome_flutter/assets/6721286/c28470f2-cfd9-4311-b708-2a5585b5e281">

**Comment by michaelspiss** [comment]
Hey, your container needs a `clipBehavior` specified if you want to crop. Since font awesome icons are not square there is always the chance that they are larger/smaller in width/height than anticipated. However, this is a limitation by font awesome and not by this library
