### ISSUE TITLE
Solid Icon showing Regular

### ISSUE THREAD

**Issue by kimberly-aureus** [fluttercommunity/font_awesome_flutter#262]
**Describe the bug**
I am calling the icon "FontAwesomeIcons.solidCopy" using either Icon wrapper/FaIcon wrapper. However despite selecting solid, it is displaying as regular.

**Expected behavior**
Icon to display as solid

**Screenshots**
<img width="318" alt="Screenshot 2024-04-08 at 5 08 12 PM" src="https://github.com/fluttercommunity/font_awesome_flutter/assets/165622082/8478d3d1-c701-43e0-9be8-fe248ed29364">
<img width="318" alt="Screenshot 2024-04-08 at 5 08 51 PM" src="https://github.com/fluttercommunity/font_awesome_flutter/assets/165622082/7b3274c6-cd1c-4d2b-92aa-745ecb3ca242">

on all devices

**Comment by TamixFixback** [comment]
> **Describe the bug**
> 
> I am calling the icon "FontAwesomeIcons.solidCopy" using either Icon wrapper/FaIcon wrapper. However despite selecting solid, it is displaying as regular.
> 
> 
> 
> **Expected behavior**
> 
> Icon to display as solid
> 
> 
> 
> **Screenshots**
> 
> <img width="318" alt="Screenshot 2024-04-08 at 5 08 12 PM" src="https://github.com/fluttercommunity/font_awesome_flutter/assets/165622082/8478d3d1-c701-43e0-9be8-fe248ed29364">
> 
> <img width="318" alt="Screenshot 2024-04-08 at 5 08 51 PM" src="https://github.com/fluttercommunity/font_awesome_flutter/assets/165622082/7b3274c6-cd1c-4d2b-92aa-745ecb3ca242">
> 
> 
> 
> on all devices
> 
>

**Comment by michaelspiss** [comment]
Hey @kimberly-aureus sorry for the late reply. This is indeed a very weird bug. I was not able to replicate it with the latest version though, so my best guess is that this was either a caching bug or fixed with the latest update.
