### ISSUE TITLE
Resolve lint warnings for newer flutter linter rules

### ISSUE THREAD

**Issue by walsha2** [fluttercommunity/font_awesome_flutter#265]
**Describe the bug**

`flutter_lints: ^4.0.0` now warns about using super parameters where applicable. This would be a simple change here to make the code compliant with `flutter_lints: ^4.0.0`.

**To Reproduce**

Update to `flutter_lints: ^4.0.0` and run linter.

**Expected behavior**

Linter suggestions are cleaned up.

**Screenshots**

![lint](https://github.com/user-attachments/assets/d9801fa4-572c-47fb-a45e-a1c85c830c2f)

**Comment by michaelspiss** [comment]
Fixed with soon to be release version 10.8.0. Thanks for creating this issue!
