### ISSUE TITLE
Add font_awesome_flutter to Flutter Arsenal

### ISSUE THREAD

**Issue by flutter-arsenal** [fluttercommunity/font_awesome_flutter#55]
font_awesome_flutter can be added to FlutterArsenal to help with reach, accessibility and ease-of-use. [Flutter Arsenal](https://flutterarsenal.com) is a directory that is being curated for Flutter libraries and tool. The best way to do is by creating an issue on [github](https://github.com/flutterarsenal/FlutterArsenal/issues/new/choose).

**Comment by iamprakash13** [comment]
#55 is that resolved. is that added to Flutter Arsenal libraries list.
