### ISSUE TITLE
How to get base64 string from icon to render icons in HTML offline?

### ISSUE THREAD

**Issue by jazzbpn** [fluttercommunity/font_awesome_flutter#56]
I want to use this plugin for HTML to render image icons. So, is there any way to get base64 string of icon?

**Comment by michaelspiss** [comment]
This plugin provides the font awesome icons for flutter. If you don't use flutter, I suggest you use the [standard way to include font awesome into your webpage](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself).

**Comment by jazzbpn** [comment]
Hello @michaelspiss I want to use the font-awesome library for the mobile application. So, how do take a license to use this library in mobile platform? Do we have to take a license for all platform separately or single license will work for all platform?

**Comment by michaelspiss** [comment]
A single license covers all platforms. Font Awesome's pricing model is based around how many **developers** are using the icons (called "seats"), not where or how often they are viewed. So if you are building your app alone, one license is sufficient for web, ios, android, etc. For more information visit https://fontawesome.com/plans.

Before you buy, please check if you actually need a pro license!

The free plan already includes many icons and all of them work out of the box with this package. Just add `font_awesome_flutter: ^8.5.0` to your `pubspec.yaml`'s dependencies and use them like any other icon in flutter: `Icon(FontAwesomeIcons.book)`. That's it.

If you need some of the pro icons (duotone are not yet supported) please follow the iconstructions over at [my fork](https://github.com/michaelspiss/font_awesome_flutter#include-pro-icons), as pro support has not been merged into the main repository yet. The pro plan (at the time of writing) costs 99$ per year and can be bought [here](https://fontawesome.com/plans).
