### ISSUE TITLE
wikipediaW  not aligned properly

### ISSUE THREAD

**Issue by shashikantshaale** [fluttercommunity/font_awesome_flutter#65]
wikipediaW icon is not aligned in the center.

Work around to make it center:
```
Align(
            alignment: Alignment.centerLeft,
            child: Icon(FontAwesomeIcons.wikipediaW),
  )
```

**Comment by brianegan** [comment]
Hi there -- yah, it's a recurring problem. The `Icon` Widget is square, while many of the Icons are rectangular. These leads to some odd alignment / cropping issues. Please use the new `FaIcon` widget instead of `Icon` :)
