### ISSUE TITLE
IconDataDuotone class missing

### ISSUE THREAD

**Issue by JuanM04** [fluttercommunity/font_awesome_flutter#76]
I think it could be and issue when parsing data from `icons.json` in `generate_font.dart`, so this line should be added:

```dart
// ...
List<String> styles = (icon['styles'] as List).cast<String>();

styles.remove('doutone');

if (styles.length > 1) {
// ...
```

**Comment by michaelspiss** [comment]
Could you elaborate on why you think the duotone styles could cause problems?

**Comment by JuanM04** [comment]
Sorry.
Because of this:

```dart
String generateIconDefinition(String iconName, String style, String unicode) {
  style = '${style[0].toUpperCase()}${style.substring(1)}';

  String iconDataSource = 'IconData$style';

  // ...
}
```

I will generate a class IconDataDuotone (which doesn't exist)

**Comment by michaelspiss** [comment]
Ah thanks, I see. In my opinion it would be better to just add the IconDataDuotone class similar to IconDataLight (all duotone icons are pro icons if I recall correctly). Outlawing a style just because we don't officially support it (yet) does not seem like a good idea to me

**Comment by JuanM04** [comment]
You would _outlaw_ it temporally. In my opinion, it's the best option
