### ISSUE TITLE
License Requirements

### ISSUE THREAD

**Issue by jmcalibuso27** [fluttercommunity/font_awesome_flutter#77]
Hi! Is it required to add license and/or attribution to FontAwesome on my app?

**Comment by michaelspiss** [comment]
See https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt for details about their license. Neither they nor this package need any further attribution except the license text/comment that comes with it.

**Comment by mhmdanas** [comment]
@michaelspiss does this mean that I don't have to do anything explicitly except using something like [`showLicensePage`](https://api.flutter.dev/flutter/material/showLicensePage.html) for example?

**Comment by michaelspiss** [comment]
That's what I understand from reading their license, explicitely [lines 21-24](https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt#L21-L24).

@brianegan it might be a good idea to add font awesome's [attribution](https://github.com/FortAwesome/Font-Awesome/blob/master/css/all.css#L2-L3) to our license file so it will be displayed in [`showLicensePage`](https://api.flutter.dev/flutter/material/showLicensePage.html)?
