### ISSUE TITLE
Is it possible to use duotone icons?

### ISSUE THREAD

**Issue by Livinglist** [fluttercommunity/font_awesome_flutter#81]
Is it possible to use duotone icons?

**Comment by michaelspiss** [comment]
Yes, duotone support has been added with the last update. You can use them provided you have a font awesome pro license. Follow [these](https://github.com/fluttercommunity/font_awesome_flutter#how-can-i-use-pro-icons) steps to install the pro icons and refer to [this guide](https://github.com/fluttercommunity/font_awesome_flutter#duotone-icons) on how to use duotone icons in you flutter app
