### ISSUE TITLE
IconDataSolid no longer accessible

### ISSUE THREAD

**Issue by boeledi** [fluttercommunity/font_awesome_flutter#84]
Hi Brian, 

Many thanks for maintaining this library.

Would it be possible to export the "src/icon_data.dart" in your package so that we can still use (without having a lint warning) this IconDataSolid() class?

Many thanks in advance,

**Comment by michaelspiss** [comment]
Hi Didier, I guess what you are trying to do is type check to figure out what type of icon you are dealing with?

**Comment by boeledi** [comment]
Hi Michael,

In fact I have a configuration that gives me the icon id (e.g. iconName = "0xf13e").  Based on this, I need to get the corresponding IconData, as follows:

`
final IconData iconData = IconDataSolid(int.parse(iconName.substring(2), radix: 16));
`

**Comment by michaelspiss** [comment]
Ah, I see. You are right, we should export `icon_data.dart` to dynamically load icons. Thanks for bringing it up, I will propose a fix immediately.

**Comment by boeledi** [comment]
Thanks so much

**Comment by brianegan** [comment]
Thanks for the bug report @boeledi and quick fix @michaelspiss! 8.8.1 published with the exported `IconDataX` classes.

**Comment by boeledi** [comment]
So many thanks for this quick fix.
