### ISSUE TITLE
FaDuotoneIcon not export?

### ISSUE THREAD

**Issue by liudonghua123** [fluttercommunity/font_awesome_flutter#86]
From the readme, I see FaDuotoneIcon, but the examples like could not explained due the FaDuotoneIcon is not export in font_awesome_flutter.
```dart
FaDuotoneIcon(
  FontAwesomeIcons.abacus,
  primaryColor: Colors.black.withOpacity(.4),
  secondaryColor: Colors.black,
);
```

**Comment by michaelspiss** [comment]
The `FaDuotoneIcon` class will be exported automatically if you have imported any duotone icons via the generator. Please refer to the "pro icons" section on how to do so.
