### ISSUE TITLE
Cannot Use Flutter font aswsome

### ISSUE THREAD

**Issue by chhinsras** [fluttercommunity/font_awesome_flutter#87]
I have correctly get the package.

But when I run it showed this error.

![image](https://user-images.githubusercontent.com/31751665/80333986-06d17780-887a-11ea-893b-180975270d1a.png)

Pub File

![image](https://user-images.githubusercontent.com/31751665/80334021-236daf80-887a-11ea-8260-7800a936992e.png)

**Comment by michaelspiss** [comment]
This is a rather interesting error, as it seems like font_awesome_flutter can't access flutter's classes. I sadly cannot reproduce this on my machine.

Could you run `flutter clean` in your project and do a rebuild to make sure this isn't some strange issue with build caching? If that doesn't work please include the output of `flutter doctor -v` and I will try my best to help you with this.

**Comment by chhinsras** [comment]
I try . but doesnt'work.

I'm not sure why, I think there is something wrong with my laptop. I reset PC and install everything again.

NOw it works

**Comment by michaelspiss** [comment]
Extreme measurements, but good to see it working now. Happy coding!
