### ISSUE TITLE
Icon images in README.

### ISSUE THREAD

**Issue by piyushchauhan** [fluttercommunity/font_awesome_flutter#88]
Since this an awesome font library it would be great to see some sample Icons as images in README itself. It will help developers know how rich this package of icons is.

**Comment by michaelspiss** [comment]
Hi, thanks for your suggestion! However, I don't think we can approriately display the diversity of icons included in font awesome with some sample icons. In my opinion the link to their website on top of the readme is sufficient.

**Comment by piyushchauhan** [comment]
@michaelspiss Yeah you are right I guess. So closing this issue.
