### ISSUE TITLE
Question: LinearGradient

### ISSUE THREAD

**Issue by Wivison** [fluttercommunity/font_awesome_flutter#91]
Hi Guys!
First of all, congratulations on the excellent work!

I have a question: is it possible to use gradient colors in solid and duotone icons?

Thank you for your attention.

PS: Using Google Translate.

**Comment by michaelspiss** [comment]
Hi, you can't use them directly via the color parameter, but a ShaderMask should work just fine. Example: https://gist.github.com/mjohnsullivan/117e7fffd283c34c5078a93330504b9f
