### ISSUE TITLE
defining a getter or field named 'FontAwesomeIcons

### ISSUE THREAD

**Issue by prakash51** [fluttercommunity/font_awesome_flutter#92]
Error: The getter 'FontAwesomeIcons' isn't defined for the class 'MyApp'

**Comment by michaelspiss** [comment]
You may have forgotten to import font_awesome_flutter - see examples. If that is not the case, please let me have a look at your code.

**Comment by prakash51** [comment]
I used the flutter clean option. Now it's working. Thank you for the quick response.

**Comment by michaelspiss** [comment]
Thanks for adding your solution!
