### ISSUE TITLE
Compiler Failed

### ISSUE THREAD

**Issue by tejas2** [fluttercommunity/font_awesome_flutter#93]
while compiling the code,
it comes up with the error ...

Compiler message:
```
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/font_awesome_flutter-8.8.1/lib/src/fa_icon.dart:102:30: Error: Getter not found: 'visible'.
      overflow: TextOverflow.visible, // Never clip.
                             ^^^^^^^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/font_awesome_flutter-8.8.1/lib/src/fa_icon.dart:144:9: Error: Method not found: 'IconDataProperty'.
        IconDataProperty('icon', icon, ifNull: '<empty>', showName: false));
        ^^^^^^^^^^^^^^^^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/font_awesome_flutter-8.8.1/lib/src/fa_icon.dart:146:20: Error: Method not found: 'ColorProperty'.
    properties.add(ColorProperty('color', color, defaultValue: null));
                   ^^^^^^^^^^^^^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/font_awesome_flutter-8.8.1/lib/src/fa_icon.dart:144:9: Error: The method 'IconDataProperty' isn't defined for the class 'FaIcon'.
 - 'FaIcon' is from 'package:font_awesome_flutter/src/fa_icon.dart' ('file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/font_awesome_flutter-8.8.1/lib/src/fa_icon.dart').
Try correcting the name to the name of an existing method, or defining a method named 'IconDataProperty'.
        IconDataProperty('icon', icon, ifNull: '<empty>', showName: false));
        ^^^^^^^^^^^^^^^^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/font_awesome_flutter-8.8.1/lib/src/fa_icon.dart:146:20: Error: The method 'ColorProperty' isn't defined for the class 'FaIcon'.
 - 'FaIcon' is from 'package:font_awesome_flutter/src/fa_icon.dart' ('file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/font_awesome_flutter-8.8.1/lib/src/fa_icon.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ColorProperty'.
    properties.add(ColorProperty('color', color, defaultValue: null));
                   ^^^^^^^^^^^^^
Compiler failed on C:\Users\tej\AndroidStudioProjects\BMI-Calculator-Flutter-Completed\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by michaelspiss** [comment]
Could you run `flutter clean` in your project and do a rebuild? If that doesn't work please include the output of flutter doctor -v and I will try my best to help you with this.

Seems to be similar to #87

**Comment by tejas2** [comment]
@michaelspiss  thanks, flutter clean & rebuild doesn't work.

**Here is the output of flutter doctor -v**


C:\Users\tej\AndroidStudioProjects\Calculator-Flutter-Completed>flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.1217], locale en-US)
    • Flutter version 1.2.1 at C:\src\flutter
    • Framework revision 8661d8aecd (1 year, 3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\tej\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\tej\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] VS Code, 32-bit edition (version 1.9.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Nokia 8 1 • PXXXX9030900497 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

C:\Users\tej\AndroidStudioProjects\Calculator-Flutter-Completed>

**Comment by michaelspiss** [comment]
Thanks! Your flutter installation is more than a year old, please run `flutter upgrade` to update to the newest version. It also seems like some android licenses have not been accepted yet, you can do that by using the 
`flutter doctor --android-licenses` command. Once you have done both of these things please do another `flutter clean` amd rebuild

**Comment by tejas2** [comment]
Thanks a lot, @michaelspiss  it worked...closing the issue.
