### ISSUE TITLE
More details about the pro icons

### ISSUE THREAD

**Issue by PHPadawan** [fluttercommunity/font_awesome_flutter#94]
I'm struggling to get the pro icons working. Where should the 'location of your choice' exactly be? Can someone provide more some details please.

**Comment by michaelspiss** [comment]
Hi, the 'location of your choice' can be anywhere you want. I always use `<project directory>/third_party/font_awesome_flutter`

**Comment by PHPadawan** [comment]
One more question, is it normal that when I ran _flutter pub get_ in my project that it throws `! font_awesome_flutter 8.8.1 from path third_party/font_awesome_flutter`?

**Comment by michaelspiss** [comment]
It's just a notice that the official font_awesome_flutter package has been replaced with the one from `third_party/font_awesome_flutter`. So yes, this is exactly what we want. I will close this issue as you have made it to this step. If you have further questions feel free to open another issue.
