### ISSUE TITLE
The method 'FaDuotoneIcon' isn't defined for the type '_MyHomePageState'

### ISSUE THREAD

**Issue by Coffiie** [fluttercommunity/font_awesome_flutter#96]
Hello, I have followed the "How can I use pro icons?" in the documentation, reproduced every step as it says in the instructions, in a new project just to demonstrate.

It seems like I am not able to use the FaDuotoneIcon class as well as the Pro Icons.

I still get the error saying "The method 'FaDuotoneIcon' isn't defined for the type '_MyHomePageState'" and "The getter 'abacus' isn't defined for the type 'FontAwesomeIcons'."

**Here is how my directory looks like:** 

**<project>/dependency_overrides/font_awesome_flutter/<all files from font_awesome_flutter-master>**
![file_structure](https://user-images.githubusercontent.com/54104668/83428797-eac87500-a3e7-11ea-9061-47bf0238d79c.jpg)

the icons.json file is in the **dependency_overrides/font_awesome_flutter/**. (Maybe I am doing this wrong? I'm not sure where to put this)

**Project pubspec.yaml:**
![project pubspec](https://user-images.githubusercontent.com/54104668/83429376-d173f880-a3e8-11ea-920b-0b7a1ddf5355.jpg)

**Font Awesome pubspec.yaml:**
![font awesome pubspec](https://user-images.githubusercontent.com/54104668/83429615-20219280-a3e9-11ea-978b-367c1e993c4e.jpg)

**The lines of code causing errors:**
![error](https://user-images.githubusercontent.com/54104668/83429761-6119a700-a3e9-11ea-8627-4626d3d99054.jpg)

**Both errors in text are defined at the start**

Please let me know the issue here, thank you!

**Comment by michaelspiss** [comment]
Hi, it looks like either the generator did not work or font_awesome_flutter has not been imported. Did you run `flutter packages get` in your example project? If yes, did you import font_awesome_flutter using `import 'package:font_awesome_flutter/font_awesome_flutter.dart';` (see [usage](https://github.com/fluttercommunity/font_awesome_flutter#usage) example)?

**Comment by Coffiie** [comment]
Yes, I ran Flutter packages get:

**! cupertino_icons 0.1.3
! font_awesome_flutter 8.8.1 from path dependency_overrides\font_awesome_flutter
Running "flutter pub get" in example...                             0.4s**

also, I am importing it the same way as in the usage example:
**
import 'package:font_awesome_flutter/font_awesome_flutter.dart';**

The import statement does not give me an error, which means the package has been imported, right?

Also, the generator worked (I saw the console window pop up and perform some operations after I ran "./tool/update.sh" in the directory).

**Comment by michaelspiss** [comment]
Ok perfect. Duotone support should be enabled automatically when there is at least one icon with duotone style available, which seems not to have happened here. I assume your font awesome license covers duotone icons (version >= 5.3.0)?

Please verify that your `dependency_overrides/font_awesome_flutter/lib/font_awesome_flutter.dart` looks something like this:
```dart
library font_awesome_flutter;

import 'package:flutter/widgets.dart';
import 'package:font_awesome_flutter/src/icon_data.dart';
export 'package:font_awesome_flutter/src/fa_icon.dart';
export 'package:font_awesome_flutter/src/icon_data.dart';
export 'package:font_awesome_flutter/src/fa_duotone_icon.dart';

// THIS FILE IS AUTOMATICALLY GENERATED!

class FontAwesomeIcons {
  static const IconData fiveHundredPx = const IconDataBrands(0xf26e);
  // ...
```

The reason why `FontAwesomeIcons.abacus` does not work is because the standard abacus style is not duotone. It should work if you use `FontAwesomeIcons.duotoneAbacus` instead.

**Comment by Coffiie** [comment]
I am contacting the buyer, regarding the license question.

My font_awesome_flutter.dart is missing  **export 'package:font_awesome_flutter/src/fa_duotone_icon.dart';** this export.

**Comment by ghenry** [comment]
Hi,

I am seeing the same, but a recase error using the update tool.

I want to use the light icons then switch to  duotone when something is selected. How do I use the light icons?

Thanks.

**Comment by ghenry** [comment]
```
~/src/font_awesome_flutter [master*]$ ./tool/update.sh 
Custom icons.json found, using local data only.
Error: Could not resolve the package 'recase' in 'package:recase/recase.dart'.
tool/generate_font.dart:4:8: Error: Not found: 'package:recase/recase.dart'
import 'package:recase/recase.dart';
       ^
tool/generate_font.dart:94:18: Error: Method not found: 'ReCase'.
  iconName = new ReCase(iconName).camelCase;
                 ^^^^^^
Error: Could not resolve the package 'recase' in 'package:recase/recase.dart'.
tool/generate_example.dart:4:8: Error: Not found: 'package:recase/recase.dart'
import 'package:recase/recase.dart';
       ^
tool/generate_example.dart:60:18: Error: Method not found: 'ReCase'.
  iconName = new ReCase(iconName).camelCase;
                 ^^^^^^
Unchanged ./lib/font_awesome_flutter.dart
Unchanged ./example/lib/icons.dart
```

I note inside `tool/generate_font.dart` there is no mention of **light**?

**Comment by ghenry** [comment]
![Screenshot from 2020-06-09 22-36-21](https://user-images.githubusercontent.com/159608/84203707-cdf40780-aaa1-11ea-93a5-a0c823815d16.png)

**Comment by michaelspiss** [comment]
Hi, the recase error is probably because you didn't run `flutter packages get` inside your local font_awesome_flutter installation (it then installs recase automatically). Please note that this is an extra step and not the `flutter packages get` you run inside your project (which depends on font_awesome_flutter). Once you have done that, run ./tool/update.sh` again and it should complete without errors and fix the problem with FaDuotoneIcon missing as well.

**Comment by ghenry** [comment]
> Hi, the recase error is probably because you didn't run `flutter packages get` inside your local font_awesome_flutter installation (it then installs recase automatically). Please note that this is an extra step and not the `flutter packages get` you run inside your project (which depends on font_awesome_flutter). Once you have done that, run ./tool/update.sh` again and it should complete without errors and fix the problem with FaDuotoneIcon missing as well.

Thanks. This worked, but I'm now seeing:

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following _TypeError was thrown building HomeScreen(dirty, dependencies: [_LocalizationsScope-[GlobalKey#54817], _InheritedTheme], state: _HomeMasterState#0839c):
type 'IconDataRegular' is not a subtype of type 'IconDataDuotone'
```

**Comment by michaelspiss** [comment]
`FaDuotoneIcon` needs an icon with duotone style. So instead of `FontAwesomeIcons.abacus` use `FontAwesomeIcons.duotoneAbacus`

**Comment by ghenry** [comment]
Ah, a docs bug then. The Pro section doesn't have that prefix. But I should
have clocked it.

Thanks.

**Comment by michaelspiss** [comment]
Oh, thanks for the notice - you are right, the example is wrong. Fixed now.

**Comment by ghenry** [comment]
Thanks. All working now. Lovely!

**Comment by ghenry** [comment]
Little screenshot for you. Feel free to delete this comment, but looks amazing. Great work!
![Screenshot_1591783645](https://user-images.githubusercontent.com/159608/84256132-725e6400-ab0b-11ea-9081-717939a98ca8.png)

**Comment by michaelspiss** [comment]
Awesome! Happy coding!

**Comment by michaelspiss** [comment]
@Coffiie I think the font awesome version you are using simply does not have any duotone icons included. You can do a quick check by opening the `icons.json` and searching for `duotone`. If there are no matches, your version is too old. I'm closing this, but feel free to open a new issue should your version support duotone.
